sudo: required

services:
  - docker

env:
  global:
    - secure: "W4B4wXcqHuH44bsz2/zxsG1JWzNESSilTyDTCdzF9/QkIa8/wCWLLCLbhYv6gY2oxEWYJKrBiAx6jO9C7d63YeR/SzPQdes2ws3qXFn4CRSekonXxX/HU4CO0f8N+em4WAZVTJD6N46DQzWNUr7ZHDACpx2ERjtXw/edbYX2TLV8uOtVXB9QBv2E+G4N70Shj9EjI75xUhmHgBUDLUJpdLLfeTydGO9eaxKwObttEqiNXhFls03Pb4Cak6sJTFd2aMkhd+6aiUnk0p60S0egEuTfFqdI/oyTydVtdkdSJY/K+cWicJcj2DyxFr7oXdMqZTCGyjZ+9mjz1TCxD61ixJjIZQZNZ4v4HhVkIXGIuA6RFk1c3ehA8RPdsT2wEkUclT/FzxDTufX9odYCnsCIfGf+5LrD4hzrEu6OmOxBUgk5C+X/bsXU8VXdxRIVNW1DL8tfRFOcwZ/I6KqBFZeR1GxGp2WJPrz+NZ91P5m2WulRyYC8MyxCMu1x3utfTBhRF+3pwZljXm1JXEUvlLUfQG9iTwNWcRH0USADCz+J2kNZyjsx/q/vMrEn+2ynjGC28XXTLUVNJlSitpOZb5uJUAFgHyzhH2flRCxMkS1fWhsA0arhI1lE+MSezeKxrlwFpS13a+uK+guevi/WxCVX1dJZZ1gDm/s3aylc3Ixrn28="
    - DOCKER_USERNAME="skwashd"

install: true

script:
  - ./build.sh

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: docker push skwashd/alpine:3.8
  on:
    branch: master
